cc_library(
    name = "fast_metrics",
    srcs = [
        "Metric.cpp",
        "Metrics.cpp",
    ],
    hdrs = [
        "CodeBlock.hpp",
        "Counter.hpp",
        "Gauge.hpp",
        "Histogram.hpp",
        "Metric.hpp",
        "Metrics.hpp",
        "build.hpp",
        "estimator/Estimator.hpp",
        "estimator/Value.hpp",
        "estimator/ExponentialRunningAverage.hpp",
        "estimator/WindowRunningAverage.hpp",
    ],
    include_prefix = "fmetrics",
    visibility = ["//visibility:public"],
)
